---
title: "Gov 50 Final Project"
author: Aimee Choi
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to factors that influence hiring or job applications.


## Proposal

Does the option to work remotely increase applications for job postings on LinkedIn? In this study, I will examine whether job postings on LinkedIn with the option to work remotely receive more higher application rates (application per view) than job postings without the option. I hypothesize that postings with the remote working option will receive more applications on average. Ever since the COVID-19 pandemic made remote working more widespread and the job market more unstable, uncertainties about their post-pandemic work have left employees experiencing anxiety and burnout; the option to work flexibly (that is, remotely) is shown to reduce this anxiety and thus make jobs more satisfactory. I will use a sample of 15,886 job postings on LinkedIn collected over two days (July 23rd and 24th) in 2023, where the unit of analysis is a job posting. My explanatory variable of interest is the option to work remotely. The option to work remotely is coded =1 for this variable, while the lack of an option to work remotely is coded =0. My outcome variable is the proportion of the number of applications the employer receives for every view they get for the job posting. I will divide the number of applications by number of views in order to obtain this value. A higher application-per-view for jobs with the remote working option would support my hypothesis. On the other hand, if the application-per-view for jobs with the remote working option is similar to or lower than that of jobs without the remote working option, my hypothesis would be disproved. 

```{r}
library(tidyverse)

job_postings
  
```

